### ISSUE TITLE
Invalid Parameter - white\r\n upon using !caption or !meme 

### ISSUE THREAD

**Issue by citruscitrus** [ExillustX/GifMemeGen#6]
![image](https://user-images.githubusercontent.com/73140849/96512353-5e9bda80-122e-11eb-8921-3709bbd599cb.png)

**Comment by exil0867** [comment]
Seems like you don't have ImageMagick installed, you can download it from here: https://imagemagick.org/script/download.php

**Comment by citruscitrus** [comment]
Ah, so when I install it should I put it into the bot? Where?

**Comment by exil0867** [comment]
Just install it on your system. That's it

**Comment by citruscitrus** [comment]
ah

**Comment by citruscitrus** [comment]
I did that and I am still getting the same error

**Comment by exil0867** [comment]
Can you check if ImageMagick installed by typing: ``convert --version`` in the command-line?

**Comment by citruscitrus** [comment]
It says "Invalid drive specification"

**Comment by exil0867** [comment]
Seems like the problem is related to your ImageMagick installation, are you on Windows?

**Comment by citruscitrus** [comment]
Yes

**Comment by exil0867** [comment]
Ok then try to reinstall ImageMagick but this time make sure to check "Add application directory to your system path" and "Install legacy utilities (e.g. convert)"

**Comment by citruscitrus** [comment]
That made it so putting "convert --version" in the command prompt work ,but I am still getting the same invalid parameter error

**Comment by exil0867** [comment]
Have you tried rebooting your system?

**Comment by citruscitrus** [comment]
That seemed to have worked, but I am getting this error now 
![image](https://user-images.githubusercontent.com/73140849/96517454-f6052b80-1236-11eb-88f9-a26460b9b4aa.png)

**Comment by exil0867** [comment]
I think that's because your user profile name has a space (PC Planet), and it results in a syntax error in the command call.
Try to rename your user profile folder so it doesn't have any space or special characters.

**Comment by citruscitrus** [comment]
I am sorry for taking so long, but I had my friend host the bot and that seemed to be the problem. Never buy a fuckin pre built lmao.
